defaults:
  - default.yaml

gpus: 1

min_epochs: 1
max_epochs: 3

# prints
enable_model_summary: False
profiler: null

# debugs
limit_train_batches: 2
limit_val_batches: 100
check_val_every_n_epoch: 2
# fast_dev_run: true
# overfit_batches: 0
# limit_test_batches: 1.0
# track_grad_norm: -1
# detect_anomaly: true
