_target_: pytorch_lightning.Trainer

gpus: [0, 1, 2, 3]

# min_epochs: 1
max_epochs: 50

resume_from_checkpoint: null
enable_model_summary: False

# number of validation steps to execute at the beginning of the training
num_sanity_val_steps: 0
# log_every_n_steps: 25
limit_val_batches: 100
check_val_every_n_epoch: 100000
